### ISSUE TITLE
No symbol files found at provided filename

### ISSUE THREAD

**Issue by MariasStory** [JPCERTCC/Windows-Symbol-Tables#1]
Hi @shu-tom,
Thanks you for the cool profiles list.
When I am trying to run vol3 offline, I am getting:
```
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80729e00000
DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrnlmp.pdb/1F9BB45B28B806E4D18925C06E924B8C-1
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility3.schemas: All validations will report success, even with malformed input
INFO     volatility3.framework.automagic: Running automagic: KernelModule    
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel

Variable	Value
Traceback (most recent call last):
  File "/usr/bin/vol3", line 10, in <module>
    volatility3.cli.main()
  File "/opt/vol3/volatility3/cli/__init__.py", line 625, in main
    CommandLine().run()
  File "/opt/vol3/volatility3/cli/__init__.py", line 333, in run
    renderers[args.renderer]().render(constructed.run())
  File "/opt/vol3/volatility3/cli/text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "/opt/vol3/volatility3/framework/renderers/__init__.py", line 212, in populate
    for (level, item) in self._generator:
  File "/opt/vol3/volatility3/framework/plugins/windows/info.py", line 158, in _generator
    kdbg = self.get_kdbg_structure(self.context, self.config_path, layer_name, symbol_table)
  File "/opt/vol3/volatility3/framework/plugins/windows/info.py", line 76, in get_kdbg_structure
    kdbg_table_name = intermed.IntermediateSymbolTable.create(context,
  File "/opt/vol3/volatility3/framework/symbols/intermed.py", line 239, in create
    raise FileNotFoundError("No symbol files found at provided filename: {}", filename)
FileNotFoundError: [Errno No symbol files found at provided filename: {}] kdbg
```
Can please assist?

**Comment by shu-tom** [comment]
This symbol table is already stored in this repository.
https://github.com/JPCERTCC/Windows-Symbol-Tables/blob/main/symbols/windows/ntkrnlmp.pdb/1F9BB45B28B806E4D18925C06E924B8C-1.json.xz

Please copy it to your Volatility 3 folder.
```
$ git clone https://github.com/JPCERTCC/Windows-Symbol-Tables.git
$ cp -R symbols/windows volatility3/volatility3/symbols
```

**Comment by MariasStory** [comment]
Hi @shu-tom,
Thank for the fast reply.
Unfortunately, I cannot get the symbols to work offline.
I did copy the proposed profile from your repo, and even from https://downloads.volatilityfoundation.org/volatility3/symbols/windows.zip
I am sure that I am missing something.
I am using docker.
Can you please share how you setup your vol3 to work offline?

**Comment by shu-tom** [comment]
My vol3 symbols folder is as berow
```
$ ls volatility3/symbols/windows/ntkrnlmp.pdb/
03A098BC85D047028437D88E4C8BBC6B-1.json.xz	3D4400784115718818EFC898413F36C4-1.json.xz	8CFB49428DC86A330CE257778E0C2F93-1.json.xz	CA8E2F01B822EDE6357898BFBF862997-1.json.xz
06A508F37B81478E855A3542E272C084-1.json.xz	3FCC539FF307DD2D9C509206D352B9AA-1.json.xz	8D8CF2E14D2D1B21CD88604AC6FDE56D-1.json.xz	CE7FFB00C20B87500211456B3E905C47-1.json.xz
110A2D89ED7A438FEFFC84F9CFDD6C00-1.json.xz	47114209A62F3B9930F6B8998DFD4A99-1.json.xz	90F5E1C8BBE1FE1FB8A714305EE06F36-1.json.xz	DA773CF3ACF6D826AED8FF5AE17E6159-1.json.xz
11BC9A513F1140CA359ECDF50F0122C1-1.json.xz	4DC173CC51EC446E895DC545DB61083E-1.json.xz	992A9A48F30EC2C58B01A5934DCE2D9C-1.json.xz	DCA4AD4BEEB4746D48F84C0125019E43-1.json.xz
15B12C74F0E177581B6B27DD4C5022C2-1.json.xz	4EF9A5375F61FE84B7EAEF54BF025C0E-1.json.xz	A15830FE2E9141BA85535AB16623CF6F-1.json.xz	DFA4F6552DD34E03B16763D22438D8FA-1.json.xz
1B4A6F5E0766C552C90710C8ACC0295C-1.json.xz	516FDC079C4E093D75F266192F75A52B-1.json.xz	A1E1C9A90091DA9805D0EBA0470BEC85-1.json.xz	E0093F3AEF15D58168B753C9488A4043-1.json.xz
1C9875F76C8F0FBF3EB9A9D7C1C27406-1.json.xz	517E128F7B7C4EA79491DE6B9B9CE190-1.json.xz	B02B752659A9454694E2378CB3C25E61-1.json.xz	E0572D333A6446129E52CBE9AE90897F-1.json.xz
1E8593423C574A72BE87EA4966E1377B-1.json.xz	5278AFF86C341677D7D7835C85B7B844-1.json.xz	B16053724B46515388FDEA9D0470D02E-1.json.xz	F22D5096197F1D22C8F5955C03CB1CED-1.json.xz
1F9BB45B28B806E4D18925C06E924B8C-1.json.xz	57850E65D6E649A8B2A137AA12ED6465-1.json.xz	B3E18239FF83427FBBCA75184BDE8388-1.json.xz	F3A4F64B6F639A058AD6F33155ACA4F6-1.json.xz
22597D0B40394E23936F6A24C6C52D5B-1.json.xz	616A94E33A4827B451B0E19C14C03792-1.json.xz	BBED7C2955FBE4522AAA23F4B8677AD9-1.json.xz	F526DBB121425697CBBF4FB22502519F-1.json.xz
287E489F93AA4C6D94B9CD1469B7F9DE-1.json.xz	641F55C592201DCC4F59FACC72EA54DA-1.json.xz	BE3E0FF92C7A93433D4A950A037EF656-1.json.xz	FC57F1C841C2C3F793D57AC134DC0EFA-1.json.xz
2B5D086A9591C3A54729282E8F43BD82-1.json.xz	769C521E4833ECF72E21F02BF33691A5-1.json.xz	BF4B4160C2CB414E9C4516DA1E7B6609-1.json.xz
339E74133576439CBCDF7E0229DA3773-1.json.xz	84924F606DCFA4BEF5C0D97C2668CF18-1.json.xz	C2EADB24A615E9472CE47C8ADD31F130-1.json.xz
35A038B1F6E2E8CAF642111E6EC66F57-1.json.xz	8B11040A5928757B11390AC78F6B6925-1.json.xz	C78AB9DBFFED445096B4DCF7FDD6E5AF-1.json.xz
```

Did you check the permissions of the copied symbol files and folders?

**Comment by MariasStory** [comment]
Hi @shu-tom,
Thanks for the info. I fixed the path and it works now.
Thanks.
